# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$dotnet\
$golang\
$helm\
$nodejs\
$java\
$kotlin\
$php\
$python\
$rlang\
$ruby\
$swift\
$terraform\
$vagrant\
$conda\
$memory_usage\
$openstack\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
${custom.architecture}\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[❯](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[custom.architecture]
description = "Architecture when using Rosetta 2"
when = """[ "$(sysctl -in sysctl.proc_translated)" = "1" ]"""
format = "[ Rosetta ](242)"
shell = ["bash", "--noprofile", "--norc"]

[custom.arch]
command = "echo $(arch)"
description = "Current Process CPU Architecture"
when = "true"
os = "macos"
symbol = "🖥"
format = "\\($symbol  $output\\)"
